import "server-only";
import React from "react";
import { Document, Page, View, Text, Image, StyleSheet, Font } from "@react-pdf/renderer";

// ETI brand tokens — same values as ETI-cohort's tailwind.config.ts
// and the reference certificate design (RC 9487007 layout), kept
// here as constants rather than reading Tailwind config at runtime,
// since @react-pdf/renderer does not consume Tailwind classes.
const COLORS = {
  navy: "#0F172A",
  royal: "#1D4ED8",
  gold: "#F59E0B",
  sky: "#38BDF8",
  white: "#FFFFFF",
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: COLORS.white,
    paddingTop: 36,
    paddingBottom: 36,
    paddingHorizontal: 48,
    fontFamily: "Helvetica",
  },
  topBar: {
    height: 10,
    backgroundColor: COLORS.navy,
    marginHorizontal: -48,
    marginTop: -36,
    marginBottom: 24,
  },
  brandRow: { alignItems: "center", marginBottom: 8 },
  brandName: { fontSize: 22, fontWeight: 700, color: COLORS.navy, letterSpacing: 2 },
  brandSub: { fontSize: 9, color: COLORS.navy, letterSpacing: 3, marginTop: 2 },
  title: {
    fontSize: 34,
    fontWeight: 700,
    color: COLORS.royal,
    textAlign: "center",
    marginTop: 20,
  },
  presentedTo: { fontSize: 11, color: "#475569", textAlign: "center", marginTop: 14 },
  recipientName: {
    fontSize: 32,
    fontWeight: 700,
    color: "#0B1220",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  bodyText: { fontSize: 11, color: "#475569", textAlign: "center", marginTop: 8 },
  certTypeText: { fontSize: 15, fontWeight: 700, color: COLORS.royal, textAlign: "center", marginTop: 4 },
  cohortText: { fontSize: 11, color: "#475569", textAlign: "center" },
  footerRow: {
    marginTop: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  footerCol: { alignItems: "center", width: "22%" },
  qrImage: { width: 64, height: 64 },
  footerLabel: { fontSize: 8, color: "#64748B", marginTop: 4, textAlign: "center" },
  certNumber: {
    position: "absolute",
    bottom: 20,
    left: 48,
    fontSize: 8,
    color: "#94A3B8",
  },
  issueDate: {
    position: "absolute",
    bottom: 20,
    right: 48,
    fontSize: 8,
    color: "#94A3B8",
  },
});

export interface CertificatePdfProps {
  recipientName: string;
  certificateTypeName: string;
  cohortName: string;
  certificateNumber: string;
  issuedAtDisplay: string; // pre-formatted, e.g. "26 October 2026"
  qrDataUrl: string; // data:image/png;base64,... — generated by lib/certificates/pdf/generate.ts, encodes the verification URL (token), never the certificate number alone
}

// Deliberately excludes: email, phone, any UUID (student/registration/
// certificate id), payment information, verification_token as
// readable text (it's only embedded inside the QR image), and any
// other internal database detail — per directive §10.
//
// Designed to support multiple certificate types (not hard-coded to
// one program) — certificateTypeName and cohortName are the only
// program-specific text; everything else is layout.
export function CertificatePdfDocument(props: CertificatePdfProps) {
  const { recipientName, certificateTypeName, cohortName, certificateNumber, issuedAtDisplay, qrDataUrl } = props;

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.topBar} />

        <View style={styles.brandRow}>
          <Text style={styles.brandName}>ELORA TECH INSTITUTE</Text>
        </View>

        <Text style={styles.title}>Certificate of Completion</Text>
        <Text style={styles.presentedTo}>This certificate is proudly presented to</Text>
        <Text style={styles.recipientName}>{recipientName}</Text>
        <Text style={styles.bodyText}>for successfully completing the</Text>
        <Text style={styles.certTypeText}>{certificateTypeName}</Text>
        {cohortName ? <Text style={styles.cohortText}>{cohortName}</Text> : null}

        <View style={styles.footerRow}>
          <View style={styles.footerCol}>
            <Text style={styles.footerLabel}>Cohort Instructor</Text>
          </View>
          <View style={styles.footerCol}>
            <Text style={styles.footerLabel}>Elora Tech Institute</Text>
          </View>
          <View style={styles.footerCol}>
            <Text style={styles.footerLabel}>Founder &amp; Managing Director</Text>
          </View>
          <View style={styles.footerCol}>
            <Image src={qrDataUrl} style={styles.qrImage} />
            <Text style={styles.footerLabel}>Scan to verify</Text>
          </View>
        </View>

        <Text style={styles.certNumber}>Certificate ID: {certificateNumber}</Text>
        <Text style={styles.issueDate}>Issue Date: {issuedAtDisplay}</Text>
      </Page>
    </Document>
  );
}
