import "server-only";
import { getAdminClient } from "../supabase/admin";
import { assertTransition } from "./workflow";
import { logAuditEvent } from "./audit";
import { generateCertificatePdf } from "./pdf/generate";
import type { CertificationRequest, Certificate } from "./types";

// Orchestrates issuance for an 'approved' certification_request.
//
// Per the directive (§15/§27): PostgreSQL and Supabase Storage
// cannot participate in one atomic transaction — a storage upload
// can succeed after a DB write, or vice versa, and there's no way to
// roll either back atomically against the other. This function is
// designed to be SAFELY RE-CALLED after a partial failure, rather
// than pretending atomicity is achievable:
//
//   1. Idempotency check: if a `certificates` row already exists for
//      this request, return it immediately — never generate a
//      second certificate for the same request. This is backed by
//      the DB's own UNIQUE constraint on certification_request_id as
//      a second line of defense against a race between two
//      concurrent issuance calls.
//   2. status -> 'issuing' (only if not already there — see below).
//   3. Insert the `certificates` row (id/number/token generated by
//      the DB trigger). If this succeeds, the certificate now
//      exists, even if steps 4-6 below fail — a retry will find it
//     in step 1 and resume from PDF generation using the *existing*
//     row rather than inserting a second one.
//   4. Generate the PDF.
//   5. Upload it to the private `certificates` bucket.
//   6. Save `pdf_path`, set request status -> 'issued'.
//
// If the process dies between 3 and 6, the request is left at
// 'issuing' with a certificate row that has `pdf_path = null`. A
// retry call finds that row in step 1, sees pdf_path is null, and
// resumes from step 4 — it does not insert a new certificates row
// (blocked by the unique constraint even if it tried).
export async function issueCertificate(requestId: string, adminEmail: string): Promise<Certificate> {
  const admin = getAdminClient();

  const { data: request, error: requestError } = await admin
    .from("certification_requests")
    .select("*")
    .eq("id", requestId)
    .single<CertificationRequest>();

  if (requestError || !request) {
    throw new Error(`certification_requests row ${requestId} not found`);
  }

  // Step 1 — idempotency check, BEFORE any status mutation.
  const { data: existing } = await admin
    .from("certificates")
    .select("*")
    .eq("certification_request_id", requestId)
    .maybeSingle<Certificate>();

  if (existing && existing.pdf_path) {
    // Already fully issued. Nothing to do — return as-is.
    return existing;
  }

  if (request.status === "approved") {
    assertTransition(request.status, "issuing");
    const { error: statusError } = await admin
      .from("certification_requests")
      .update({ status: "issuing" })
      .eq("id", requestId)
      .eq("status", "approved"); // optimistic guard against a concurrent second caller

    if (statusError) throw statusError;

    await logAuditEvent({
      requestId,
      actorType: "admin",
      actorEmail: adminEmail,
      eventType: "issuance_started",
    });
  } else if (request.status !== "issuing") {
    // Not approved and not already mid-issuance — refuse rather than
    // silently proceeding from an unexpected state.
    throw new Error(
      `Cannot issue certificate for request in status '${request.status}'; expected 'approved' or 'issuing'.`
    );
  }

  let certificate = existing;

  try {
    if (!certificate) {
      // Step 3 — insert the certificate row. Identifiers are
      // generated by the DB trigger (see migration 001).
      const { data: inserted, error: insertError } = await admin
        .from("certificates")
        .insert({
          certification_request_id: requestId,
          student_id: request.student_id,
          cohort_id: request.cohort_id,
          certificate_type_id: request.certificate_type_id,
          issued_by: adminEmail,
        })
        .select("*")
        .single<Certificate>();

      if (insertError) {
        // A unique_violation here means a concurrent call already
        // inserted the row first — re-fetch and continue from there
        // instead of treating it as a hard failure.
        const { data: raceWinner } = await admin
          .from("certificates")
          .select("*")
          .eq("certification_request_id", requestId)
          .maybeSingle<Certificate>();
        if (!raceWinner) throw insertError;
        certificate = raceWinner;
      } else {
        certificate = inserted;
      }
    }

    // Steps 4-5 — generate + upload the PDF.
    const { data: student } = await admin
      .from("students")
      .select("full_name")
      .eq("id", request.student_id)
      .single();
    const { data: cohort } = await admin
      .from("cohorts")
      .select("name")
      .eq("id", request.cohort_id)
      .single();
    const { data: certType } = await admin
      .from("certificate_types")
      .select("name")
      .eq("id", request.certificate_type_id)
      .single();

    const pdfBuffer = await generateCertificatePdf({
      recipientName: student?.full_name ?? "Unknown Student",
      certificateTypeName: certType?.name ?? "Certificate of Completion",
      cohortName: cohort?.name ?? "",
      certificateNumber: certificate.certificate_number,
      issuedAt: certificate.issued_at,
      verificationToken: certificate.verification_token,
    });

    const objectPath = `${certificate.certificate_number}.pdf`;
    const { error: uploadError } = await admin.storage
      .from("certificates")
      .upload(objectPath, pdfBuffer, { contentType: "application/pdf", upsert: true });

    if (uploadError) throw uploadError;

    // Step 6 — finalize.
    const { data: finalCertificate, error: finalizeError } = await admin
      .from("certificates")
      .update({ pdf_path: objectPath })
      .eq("id", certificate.id)
      .select("*")
      .single<Certificate>();

    if (finalizeError) throw finalizeError;

    assertTransition("issuing", "issued");
    const { error: finalStatusError } = await admin
      .from("certification_requests")
      .update({ status: "issued" })
      .eq("id", requestId)
      .eq("status", "issuing");

    if (finalStatusError) throw finalStatusError;

    await logAuditEvent({
      requestId,
      certificateId: finalCertificate.id,
      actorType: "admin",
      actorEmail: adminEmail,
      eventType: "certificate_issued",
      metadata: { certificateNumber: finalCertificate.certificate_number },
    });

    return finalCertificate;
  } catch (err) {
    // Deliberately leave `status = 'issuing'` on failure rather than
    // reverting to 'approved' — see workflow.ts comment. The
    // certificate row (if it was created) is left as-is with a null
    // pdf_path so a retry resumes correctly.
    await logAuditEvent({
      requestId,
      certificateId: certificate?.id ?? null,
      actorType: "system",
      eventType: "issuance_failed",
      notes: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}
